openapi: 3.0.0
info:
  title: Contacts API
  description: API for storing and retrieving contact information.
  version: 1.0.0
servers:
  - url: https://contacts-api-h2ow.onrender.com/api-docs
paths:
  /contacts:
    get:
      summary: Retrieve all contacts
      responses:
        '200':
          description: A list of contacts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
    post:
      summary: Create a new contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '201':
          description: Contact created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
  /contacts/{id}:
    get:
      summary: Retrieve a contact by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the contact
          schema:
            type: string
      responses:
        '200':
          description: A single contact
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
        '404':
          description: Contact not found
    put:
      summary: Update a contact by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the contact
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        '200':
          description: Contact updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
        '404':
          description: Contact not found
    delete:
      summary: Delete a contact by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the contact
          schema:
            type: string
      responses:
        '204':
          description: Contact deleted
        '404':
          description: Contact not found
components:
  schemas:
    Contact:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        favoriteColor:
          type: string
        birthday:
          type: string
          format: date
      required:
        - firstName
        - lastName
        - email
        - favoriteColor
        - birthday